title: DailyBuddy
author:
  name: wirvsvirus Hackathon
  email: 
description: > # this means to ignore newlines
  Eine feste Tagesstruktur ist in Krisenzeiten vor allem für Menschen mit psychischen Erkrankungen wichtig. 
  Wenn der gewohnte Tagesablauf plötzlich ausfällt, kann dies zu einer Verschlechterung der psychischen Gesundheit führen. 
  DailyBuddy wird eine App für Android und iOS, die Unterstützung dabei bietet, feste Tagesabläufe zu schaffen und beizubehalten.
type: open source # Choose one from "open source", "free", freemium, ad supported, commercial
google_analytics: UA-NNNNNNNN-N
links:
  app_store: https://apps.apple.com/
  google_play: https://play.google.com/
  github: https:///github.com/Felixduelmer/Tagesstruktur_Helper
theme: mobikit
plugins:
 - jekyll-seo-tag

lang: de

static-files:
  image: 